// This file is automatically generated by i18next-cli. Do not edit manually.
interface Resources {
  "commons": {
    "actions": {
      "chat": "Chat",
      "clear-all": "Clear All",
      "clear-confirmation": "Click again to clear",
      "global-traits": {
        "desc": "The prompt will be append into the query when you skid your homework to personalize the response.",
        "placeholder": "You're a smart assistant that helps the user with the homework.",
        "submit-btn": "Submit",
        "title": "Edit Global Traits",
        "trigger": "Global Traits Editor"
      },
      "processing": "Processing...",
      "scan": "Let's Skid",
      "settings": "Settings",
      "title": "Add Homework"
    },
    "ai-client": {
      "openai": {
        "requires-responses-api-online-search": "Using online search requires Responses API to be enabled",
        "requires-responses-api-pdf": "Using PDF recognition requires Responses API to be enabled",
        "web-search-not-supported": "Model {{model}} does not support web search, continuing without it"
      }
    },
    "chat-page": {
      "actions": {
        "back": "Back to Scanner",
        "close-sidebar": "Close Sidebar",
        "delete-chat": "Delete Chat",
        "new-chat": "New Chat",
        "open-settings": "Settings",
        "search": "Search chats..."
      },
      "composer": {
        "aigc-disclaimer": "AI can make mistakes. Verify important information.",
        "placeholder": "Ask a question or paste a problem...",
        "send": "Send",
        "sending": "Sending..."
      },
      "conversation": {
        "empty": "Select a chat or start a new one to begin.",
        "empty-title": "No conversation selected"
      },
      "errors": {
        "missing-key": "{{provider}} needs an API key before you can chat.",
        "no-model": "Please set a model name before chatting.",
        "no-source": "Please enable at least one source with an API key in Settings.",
        "send-failed": "Failed to send message: {{error}}",
        "unsupported": "The selected model does not support conversations."
      },
      "history": {
        "empty": "No chats yet. Start a conversation.",
        "title": "History",
        "unknown-source": "Unknown provider",
        "untitled": "New chat"
      },
      "source": {
        "empty": "No models found.",
        "model": "Model name",
        "model-placeholder": "gpt-4.1-mini or models/gemini-2.5-pro",
        "search": "Search model...",
        "section": "Model",
        "select": {
          "placeholder": "Select a model"
        }
      },
      "subtitle": "Discuss problems with your configured models.",
      "title": "SkidHomework Chat"
    },
    "dev": {
      "copy": {
        "success": "Copied"
      }
    },
    "import-settings-page": {
      "confirm": {
        "alert": {
          "description": "Only import configurations from sources you trust. Otherwise it may cause a privacy leak. Use at your own risk.",
          "title": "Security Check"
        },
        "buttons": {
          "cancel": "Cancel",
          "confirm": "Yes, Import"
        },
        "description": "Do you want to add this configuration to your settings?",
        "fields": {
          "base": "Base URL:",
          "model": "Model Name:",
          "name": "Name:",
          "provider": "Provider:"
        },
        "title": "Import AI Model"
      },
      "error": {
        "home": "Return Home",
        "parse-failed": "Failed to parse configuration. The link might be broken.",
        "title": "Error"
      },
      "loading": {
        "parsing": "Parsing configuration..."
      },
      "success": {
        "buttons": {
          "home": "Let's Skid",
          "settings": "Settings",
          "undo": "Undo"
        },
        "description": "The AI model <strong>{{name}}</strong> has been successfully imported.",
        "title": "You're all set!"
      }
    },
    "improve-dialog": {
      "description": "Generate a more detailed solution using the current solution and your prompt.",
      "placeholder": "Make it more detailed...",
      "submit": "Submit",
      "title": "Improve the Solution",
      "toasts": {
        "failed": {
          "description": "Something went wrong: {{error}}",
          "parse": "Failed to parse response, see the developer tools for more details.",
          "title": "Failed to improve your solution"
        },
        "no-key": {
          "description": "Please set an API key for {{provider}} in Settings to continue.",
          "title": "You're almost there"
        },
        "no-source": {
          "description": "Enable at least one AI provider in Settings before improving a solution.",
          "title": "No AI sources"
        },
        "processing": {
          "description": "Improving your solution with AI...Please wait for a while...",
          "title": "Processing"
        }
      },
      "trigger": "Improve the Solution"
    },
    "init-page": {
      "features": {
        "camera": "Snap homework and get step-by-step help.",
        "setup": "Fast setup — paste your Gemini API key and go.",
        "telemetry": "No telemetry or spammy calls. Just the Gemini API."
      },
      "footer": {
        "notice": "Licensed under GPLv3, created by cubewhy.",
        "source": "Source Code"
      },
      "form": {
        "advanced": {
          "base-url-helper": "Leave blank to use the default endpoint for {{provider}}.",
          "base-url-label": "API Base URL (optional)",
          "base-url-placeholder": "Default endpoint for {{provider}}",
          "title": "Advanced"
        },
        "api-hint": "Get an API key at <link>Google AI Studio</link>.",
        "api-hint-openai": "Get an API key at <link>OpenAI Dashboard</link>.",
        "key-placeholder": "{{provider}} API Key",
        "provider": {
          "label": "AI provider"
        },
        "storage-note": "We store your key locally using encrypted browser storage and never send it to our servers.",
        "submit": "Get My Time Back!"
      },
      "headline": {
        "highlight": "Welcome to SkidHomework",
        "subtitle": "Escape the homework grind."
      },
      "intro": "Prefer Khan Academy–style self-study but still get stuck with endless assignments? SkidHomework runs locally, respects your privacy, and helps you focus on learning instead of busywork.",
      "preview": {
        "hints": "Hints",
        "ocr": "OCR",
        "steps": "Steps",
        "title": "Homework Camera"
      },
      "tagline": "Local • Private • Free"
    },
    "inspect-dialog": {
      "answer": "Answer",
      "close": "Close",
      "copy": {
        "success": "Copied"
      },
      "desc": "Review the AI generated Markdown content.",
      "explanation": "Explanation",
      "online-search": "Online Search",
      "problem": "Problem",
      "title": "Inspect Details"
    },
    "md": {
      "diagram": {
        "view-code": "View Code",
        "view-diagram": "View Diagram"
      },
      "generating-diagram": "Generating diagram..."
    },
    "preview": {
      "drag-tip": "You can drag or paste your files to this panel.",
      "drag-tip-mobile": "Tap a card to zoom in. Swipe left or right to review everything.",
      "drop-cancel": "Drag here to cancel",
      "file-type": {
        "pdf": "PDF",
        "unknown": "Unknown type"
      },
      "image-alt": "Homework preview",
      "no-files": "No files yet. Upload or take a photo to begin.",
      "remove": {
        "aria": "Remove File",
        "menu-item": "Remove"
      },
      "rename": {
        "dialog": {
          "confirm": "Confirm",
          "desc": "Please enter the new name for the file",
          "new-name": "New Name",
          "title": "Rename File"
        },
        "menu-item": "Rename"
      },
      "supported-types": "Supports images, text, Markdown, JSON, etc.",
      "tip": "Hint: double click to focus file on solution area, single click to preview in full screen",
      "title": "Preview"
    },
    "problem-list": {
      "item-label": "Problem {{index}}"
    },
    "scan-page": {
      "discussions-btn": "Discussions",
      "errors": {
        "missing-key": "Missing API key for {{provider}}.",
        "no-client": "No AI client available for the selected source.",
        "parsing-failed": "Failed to parse the AI response.",
        "processing-failed": {
          "answer": "Please check the console for errors and try again.",
          "explanation": "{{error}}",
          "problem": "Processing failed after multiple retries."
        }
      },
      "footer": {
        "license": "Licensed under GPL-3.0.",
        "slogan": "Students' lives matter",
        "source": "Source code"
      },
      "loading": "Loading...",
      "mobile": {
        "empty": "Add a photo or PDF to get started.",
        "hint-pdf": "Enable a Gemini or OpenAI (Responses API enabled) source in Settings to allow PDF uploads.",
        "hint-ready": "You're ready to scan. Tap “Let's Skid” when you're set.",
        "status": "{{count}} file ready",
        "status_plural": "{{count}} files ready",
        "tabs": {
          "capture": "Capture",
          "preview": "Review"
        }
      },
      "tip": "We never upload without your action.",
      "title": "Scan your homework",
      "toasts": {
        "all-processed": {
          "description": "There are no pending or failed files to scan.",
          "title": "All files processed"
        },
        "done": {
          "description": "Your homework has been processed.",
          "title": "All done!"
        },
        "error": {
          "description": "Something went wrong during the process. Please check the console.",
          "title": "An unexpected error occurred"
        },
        "fallback": {
          "description": "Primary model failed, retrying with fallback model {{model}}...",
          "title": "Switching to fallback model"
        },
        "no-key": {
          "description": "Please set an API key for {{provider}} in Settings.",
          "title": "You're almost there"
        },
        "no-model": {
          "description": "Please choose a model for {{provider}} in Settings before scanning.",
          "title": "Model required"
        },
        "no-source": {
          "description": "Enable at least one AI provider with an API key in Settings before scanning.",
          "title": "No AI sources configured"
        },
        "pdf-blocked": {
          "description": "Enable a Gemini or OpenAI (Responses API enabled) source to process PDF files.",
          "title": "PDF uploads disabled"
        },
        "post-processing": {
          "description": "Your image was still post-processing. Please wait for a while.",
          "title": "Still processing..."
        },
        "retry": {
          "description": "Attempt {{attempt}} failed: {{error}}. Retrying in {{delay}} seconds...",
          "title": "Request failed, retrying"
        },
        "retry-exhausted": {
          "description": "All {{maxRetries}} retries for {{source}} failed.",
          "title": "Retries exhausted"
        },
        "unsupported-file": {
          "description": "Your file with mime type {{mimeType}} is currently not supported by SkidHomework.",
          "title": "Unsupported file type"
        },
        "working": {
          "description": "Sending {{count}} file(s) to your AI sources...",
          "title": "Working..."
        }
      },
      "two-stage": {
        "fix-format": "Your previous output could not be parsed. Please re-output ALL questions strictly following the required format: each question must have ### PROBLEM_TEXT, ### EXPLANATION (with #### Step N), and ### ANSWER sections, separated by ---PROBLEM_SEPARATOR---.",
        "solve-instruction": "The following is one question recognized from an image. Solve ONLY this question and strictly follow the output format (### PROBLEM_TEXT / ### EXPLANATION / ### ANSWER)."
      }
    },
    "settings-page": {
      "advanced": {
        "custom-base-url": {
          "helper": "Leave blank to use the default endpoint for {{provider}}.",
          "placeholder": "https://example.com/v1",
          "title": "Custom API base URL"
        },
        "desc": "Extras that affect uploads and the interface.",
        "explanation": {
          "mode": {
            "everything": "Show everything to me",
            "steps": "Only show hits when I need"
          },
          "search-placeholder": "Search modes...",
          "title": "Explanation Mode"
        },
        "image-post-processing": {
          "enhancement": "Enable Image Enhancement",
          "title": "Image Post-processing"
        },
        "title": "Advanced Settings",
        "ui": {
          "clear-dialog-on-submit": "Clear dialog after submit",
          "title": "UI"
        }
      },
      "api-credentials": {
        "advanced": {
          "custom-url": "Custom URL",
          "enable-responses-api": "Enable Responses API",
          "openai-default": "OpenAI (Default)",
          "openrouter": "OpenRouter",
          "quick-preset": "Quick Preset Provider",
          "quick-preset-placeholder": "Select preset provider...",
          "responses-api-tip": "Hint: Enabling the new API allows OpenAI models to read PDFs and perform web searches. These features are unavailable without this API.",
          "switched-openai": "Reset to OpenAI default",
          "switched-openrouter": "Switched to OpenRouter",
          "title": "Advanced Options",
          "web-search-tool": {
            "auto": "Auto (based on model)",
            "custom": "Custom",
            "custom-placeholder": "Enter custom tool name...",
            "label": "Web Search Tool Type",
            "placeholder": "Select tool type...",
            "tip": "Choose the web search tool type for the Responses API. Auto will select based on the model name.",
            "web-search": "web_search",
            "web-search-preview": "web_search_preview"
          }
        },
        "applied": "API key saved.",
        "desc": "Store API keys locally for each AI provider. They never leave your browser.",
        "label": "API Key",
        "name": {
          "label": "Source name",
          "placeholder": "Friendly name shown in the app"
        },
        "placeholder": "Enter your {{provider}} API key",
        "title": "API Credentials"
      },
      "appearance": {
        "desc": "Choose how SkidHomework looks and which language it uses.",
        "language": {
          "desc": "Switch the interface language.",
          "label": "Language",
          "options": {
            "en": "English",
            "zh": "中文"
          }
        },
        "theme": {
          "desc": "Use the system preference or pick a fixed mode.",
          "label": "Theme",
          "options": {
            "dark": "Dark",
            "light": "Light",
            "system": "System"
          }
        },
        "title": "Appearance & Language"
      },
      "back": "Back",
      "clear-input": "Clear",
      "heading": "SkidHomework Settings",
      "model": {
        "desc": "Choose or type the model name used for requests.",
        "fallback": {
          "desc": "Automatically switch to this model when the primary model fails",
          "label": "When selected model is unavailable, fall back to",
          "none": "None"
        },
        "fast-model": {
          "desc": "A lightweight model used for the first recognition step, e.g. a faster model on your relay. Leave empty to use the same model as solving.",
          "label": "Segmentation model (optional)",
          "placeholder": "Leave empty to use the current model"
        },
        "fetch": {
          "error": "Failed to fetch models for {{provider}}. Check your API key or base URL."
        },
        "manual": {
          "apply": "Apply",
          "desc": "Enter a model name manually if it is not listed.",
          "placeholder": "Model identifier",
          "select-provider": "Select provider",
          "title": "Custom model"
        },
        "max-retries": {
          "label": "Max retries",
          "tip": "Maximum number of automatic retries when API calls fail (0-10). Set to 0 to disable retries."
        },
        "refresh": "Refresh models",
        "sel": {
          "empty": "No models found.",
          "none": "No model selected",
          "search": "Search model...",
          "unknown": "Unknown model ({{name}})"
        },
        "show-selector-in-scanner": "Show model selector in scanner",
        "title": "Model Configuration",
        "two-stage": {
          "desc": "Quickly recognizes the questions first, then solves each one independently in parallel - much faster than one full-page pass. Disable to fall back to the original full-page solve.",
          "label": "Two-stage fast scanning (segment first, then solve in parallel)"
        }
      },
      "openai": {
        "poll-interval": {
          "desc": "How long to wait between response status checks.",
          "title": "Polling interval (ms)"
        },
        "poll-timeout": {
          "desc": "Maximum time to wait for a response before failing.",
          "title": "Polling timeout (ms)"
        }
      },
      "reset": "Reset",
      "shortcuts": {
        "actions": {
          "adb-screenshot": {
            "description": "Capture the connected Android device's screen via ADB.",
            "label": "ADB screenshot"
          },
          "camera": {
            "description": "Launches the device camera to capture homework.",
            "label": "Take photo"
          },
          "clear-all": {
            "description": "Removes every uploaded item and solution.",
            "label": "Clear all"
          },
          "open-chat": {
            "description": "Jump straight to the chat workspace.",
            "label": "Open chat"
          },
          "open-global-traits-editor": {
            "description": "Open the editor dialog to edit global traits (prompt)",
            "label": "Open Global Traits Editor"
          },
          "open-settings": {
            "description": "Opens this settings page from anywhere in the app.",
            "label": "Open settings"
          },
          "start-scan": {
            "description": "Sends all pending items to your AI sources.",
            "label": "Start scan"
          },
          "text-input": {
            "description": "Open text input dialog.",
            "label": "Text Input"
          },
          "upload": {
            "description": "Opens the file picker for selecting files.",
            "label": "Upload files"
          }
        },
        "clear": "Clear",
        "desc": "Customize the keys used for common actions. Leave blank to disable a shortcut.",
        "manual": {
          "invalid": "Enter a valid shortcut using modifier keys plus a key.",
          "placeholder": "Type shortcut (e.g. Ctrl+1)"
        },
        "recording": "Press keys…",
        "reset": "Reset to defaults",
        "title": "Keyboard shortcuts",
        "unassigned": "Unassigned"
      },
      "sources": {
        "active": {
          "badge": "Active",
          "label": "Active source"
        },
        "add": {
          "address": "API Base Url (Optional)",
          "cancel": "Cancel",
          "confirm": "Add source",
          "key": "API Key",
          "key-placeholder": "abcdef",
          "label": "Add AI source",
          "name": "Display name (optional)",
          "name-placeholder": "e.g. Classroom Gemini",
          "provider": "Provider",
          "success": "Added {{name}}.",
          "title": "Add AI source"
        },
        "desc": "Manage enabled AI providers and choose which one to configure.",
        "enabled": {
          "label": "Enabled sources",
          "toggle": "Enabled"
        },
        "make-active": "Set active",
        "option": "{{name}} • {{provider}}",
        "providers": {
          "gemini": "Gemini",
          "openai": "OpenAI"
        },
        "remove": {
          "error": "Keep at least one AI source.",
          "label": "Remove source",
          "success": "Removed {{name}}."
        },
        "share": {
          "dialog": {
            "copy": "Copy",
            "desc": "Scan the QR code or copy the link below. Treat this URL like a password.",
            "title": "Share AI Source"
          },
          "label": "Share source"
        },
        "title": "AI Sources"
      },
      "thinking": {
        "budget": "Thinking budget",
        "desc": "Adjust advanced thinking parameters for supported providers.",
        "online-search": {
          "desc": "Allow the assistant to call web search tools when needed.",
          "show-toggle-in-scanner": "Show online search toggle in scanner",
          "title": "Online Search Settings",
          "toggle": {
            "disabled": "Enable online search",
            "enabled": "Enabled online search",
            "settings": "Online search"
          }
        },
        "title": "Thinking Settings",
        "tokens-unit": "tokens"
      },
      "traits": {
        "desc": "Define the assistant's persona or extra instructions.",
        "placeholder": "e.g., You are a helpful assistant that speaks in a friendly and professional tone.",
        "title": "System Prompt (Traits)"
      }
    },
    "solution-viewer": {
      "answer": "Answer",
      "chat": {
        "button": "Chat about this",
        "context": {
          "answer": "Answer:\n{{answer}}",
          "explanation": "Explanation:\n{{explanation}}",
          "intro": "The learner is reviewing the following work:",
          "problem": "Problem:\n{{problem}}"
        },
        "default-title": "Homework chat",
        "fallback": {
          "answer": "Answer not available.",
          "explanation": "Explanation not available.",
          "problem": "Problem not available."
        },
        "no-problem": {
          "description": "Choose a problem before starting a chat.",
          "title": "Select a problem first"
        },
        "no-source": {
          "description": "Configure an AI source with an API key in Settings to chat.",
          "title": "No model available"
        },
        "prefill": {
          "intro": "I'd like help understanding this problem.",
          "outro": "Can you walk me through it step by step?"
        }
      },
      "copy": {
        "button": "Copy answer",
        "failed": {
          "description": "Please copy manually.",
          "title": "Copy failed"
        },
        "success": {
          "description": "Answer copied to clipboard.",
          "title": "Copied"
        }
      },
      "explanation": "Explanation",
      "navigation": {
        "next-image": "File ⟶",
        "next-problem": "Next",
        "prev-image": "⟵ File",
        "prev-problem": "Prev"
      },
      "online-search": {
        "placeholder": "No search indices provided.",
        "title": "Online search results"
      },
      "open-preview": "open preview",
      "progress": {
        "prefix": "Problem",
        "suffix": "of {{total}}"
      },
      "source-image": "Source file:"
    },
    "solutions": {
      "analyzing": "Analyzing... extracting problems and solutions from your files.",
      "export": {
        "answer-label": "Answer",
        "button": "Export as Markdown",
        "document-title": "Homework Solutions",
        "empty": {
          "description": "Run a scan and wait for results before exporting.",
          "title": "Nothing to export"
        },
        "error": {
          "description": "Something went wrong while creating the markdown file.",
          "title": "Export failed"
        },
        "explanation-label": "Explanation",
        "filename-prefix": "homework-solutions",
        "more-options": "More export options",
        "page-heading": "Page {{index}} · {{name}}",
        "placeholders": {
          "answer": "_No answer provided._",
          "explanation": "_No explanation provided._",
          "problem": "_No problem content provided._"
        },
        "problem-heading": "Problem {{index}}",
        "problem-label": "Problem",
        "success": {
          "description": "Your solutions file is ready.",
          "title": "Markdown downloaded"
        },
        "word-button": "Export as Word (printable)",
        "word-error": {
          "description": "Something went wrong while creating the Word file.",
          "title": "Word export failed"
        },
        "word-exporting": "Generating Word...",
        "word-success": {
          "description": "Each problem is an image you can resize and re-space in Word, then print directly.",
          "title": "Word document downloaded"
        }
      },
      "file-label": "File {{fileName}} • {{source}}",
      "focus-region-aria": "Solutions keyboard focus region (Tab/Shift+Tab for problems, Space/Shift+Space for files)",
      "gesture-hint": "Swipe left or right to switch problems.",
      "idle": "No solutions yet. Add files and click \"Let's Skid\" to see results here.",
      "status": {
        "failed": "Failed to process this file. Please try again.",
        "pending": "Processing in progress...",
        "stream": "Reasoning...",
        "success": "No problems were detected in this file.",
        "success-with-provider": "Solved by {{provider}}."
      },
      "streaming": {
        "placeholder": "AI is thinking...",
        "title": "AI Output"
      },
      "tabs": {
        "fallback": "File {{index}}"
      },
      "title": "Solutions",
      "toggle-preview": "Toggle Preview"
    },
    "sources": {
      "adb": "ADB",
      "camera": "Camera",
      "upload": "Upload"
    },
    "upload-area": {
      "adb": {
        "capture-timeout": "ADB screenshot timed out. Please check the connection and try again.",
        "connect": "ADB Connect",
        "connecting": "Connecting...",
        "menu-aria-label": "ADB Menu",
        "reconnect": "Reconnect ADB",
        "screenshot": "ADB Screenshot",
        "screenshot-busy": "Capturing...",
        "screenshot-hint": "Capture a screenshot from a connected Android device via ADB (WebUSB)"
      },
      "camera-help-aria": "Camera help",
      "camera-tip": {
        "close": "Got it",
        "intro": "The <takePhoto>Take Photo</takePhoto> button uses the browser's native camera picker (<capture>capture=\"environment\"</capture>). On phones, it opens the camera directly. On desktops, it usually falls back to the file chooser.",
        "tips": ["Prefer natural light and avoid glare.", "Fill the frame with the problem. Keep text sharp.", "One question per shot yields better recognition."],
        "title": "Taking photos on different devices"
      },
      "pdf-disabled": "PDF uploads are available only when a Gemini or OpenAI (Response API enabled) source is enabled.",
      "take-photo": "Camera",
      "text-input": {
        "button": "Text",
        "description": "Paste or type the problem content directly.",
        "placeholder": "Enter problem here...",
        "submit": "Confirm",
        "title": "Input Problem Text"
      },
      "toasts": {
        "adb-failed": "Something went wrong with ADB: {{error}}",
        "webusb-not-supported": "WebUSB is not supported in this browser."
      },
      "upload": "Upload Files",
      "upload-tip": "Images and text files are supported. PDFs require an active Gemini or OpenAI (Responses API enabled) source."
    },
    "uploads-info": {
      "selected": "Selected"
    }
  }
}

export default Resources;
